# Generated by Django 2.0.3 on 2018-04-21 11:11

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedAnt', '0002_projectteam_shortname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectteam',
            name='Introduction',
            field=DjangoUeditor.models.UEditorField(verbose_name='项目组简介'),
        ),
        migrations.AlterField(
            model_name='projectteam',
            name='Name',
            field=models.CharField(max_length=20, verbose_name='项目组名称'),
        ),
        migrations.AlterField(
            model_name='projectteam',
            name='ShortName',
            field=models.CharField(max_length=20, null=True, verbose_name='英文缩写'),
        ),
    ]
