# Generated by Django 2.0.3 on 2018-04-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedAnt', '0003_auto_20180421_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectteam',
            name='Name',
        ),
        migrations.AddField(
            model_name='projectteam',
            name='TeamName',
            field=models.CharField(max_length=50, null=True, verbose_name='项目组名称'),
        ),
    ]
