# Generated by Django 2.0.3 on 2018-04-21 12:09

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedAnt', '0004_auto_20180421_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='ImagePath',
            field=DjangoUeditor.models.UEditorField(verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='项目组名称'),
        ),
    ]
