# Generated by Django 2.0.3 on 2018-05-15 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RedAnt', '0010_auto_20180515_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
