# Generated by Django 2.0.3 on 2018-05-17 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RedAnt', '0011_auto_20180515_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningresources',
            name='Name',
        ),
        migrations.AddField(
            model_name='learningresources',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='learningresources',
            name='fileField',
            field=models.FileField(default=django.utils.timezone.now, upload_to='Media/learningResourses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningresources',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
