# Generated by Django 2.0.3 on 2018-05-22 08:31

import RedAnt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedAnt', '0014_invitecode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZhangJie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kecheng', models.CharField(max_length=21)),
                ('name', models.CharField(max_length=21)),
            ],
        ),
        migrations.CreateModel(
            name='ZhangJieSmall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=21)),
                ('video', models.FileField(upload_to=RedAnt.models.get_upload_path)),
                ('video_desc', models.CharField(blank=True, default='', max_length=1024)),
                ('content', models.CharField(blank=True, default='', max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='ZhangJieSmallPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=RedAnt.models.get_upload_path)),
            ],
        ),
        migrations.AddField(
            model_name='zhangjiesmall',
            name='pics',
            field=models.ManyToManyField(to='RedAnt.ZhangJieSmallPic'),
        ),
        migrations.AddField(
            model_name='zhangjie',
            name='details',
            field=models.ManyToManyField(to='RedAnt.ZhangJieSmall'),
        ),
    ]
