# Generated by Django 2.0.3 on 2018-05-22 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RedAnt', '0015_auto_20180522_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zhangjie',
            name='details',
        ),
        migrations.RemoveField(
            model_name='zhangjiesmall',
            name='pics',
        ),
        migrations.DeleteModel(
            name='ZhangJie',
        ),
        migrations.DeleteModel(
            name='ZhangJieSmall',
        ),
        migrations.DeleteModel(
            name='ZhangJieSmallPic',
        ),
    ]
