# Generated by Django 2.0.3 on 2018-05-22 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RedAnt', '0017_auto_20180522_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningresources',
            old_name='teamName',
            new_name='teamId',
        ),
    ]
