# Generated by Django 2.0.3 on 2018-05-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedAnt', '0018_auto_20180522_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='ImagePath',
            field=models.CharField(max_length=100, null=True, verbose_name='图片'),
        ),
    ]
