# Generated by Django 2.0.3 on 2018-05-31 10:05

import DjangoUeditor.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RedAnt', '0021_auto_20180528_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lpost',
            name='Content',
            field=DjangoUeditor.models.UEditorField(verbose_name='回复'),
        ),
        migrations.AlterField(
            model_name='lpost',
            name='postedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
