# Generated by Django 2.0.3 on 2018-06-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedAnt', '0024_contactus_introduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileField', models.FileField(upload_to='index/poster/')),
            ],
        ),
    ]
