# Generated by Django 2.0.3 on 2018-06-04 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RedAnt', '0027_projectteam_groupphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True, verbose_name='课程名称')),
                ('ShortName', models.CharField(max_length=100, null=True, verbose_name='英文缩写')),
            ],
        ),
        migrations.AddField(
            model_name='zhangjie',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RedAnt.Course'),
            preserve_default=False,
        ),
    ]
