# Generated by Django 2.0.3 on 2018-06-04 10:47

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RedAnt', '0028_auto_20180604_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Introduction',
            field=DjangoUeditor.models.UEditorField(default=1, verbose_name='课程简介'),
            preserve_default=False,
        ),
    ]
