# Generated by Django 2.0.3 on 2018-06-04 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RedAnt', '0029_course_introduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zhangjiesmall',
            name='pics',
        ),
        migrations.AddField(
            model_name='zhangjiesmall',
            name='zhangJie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RedAnt.ZhangJie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zhangjiesmallpic',
            name='zhangJiesmall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RedAnt.ZhangJieSmall'),
            preserve_default=False,
        ),
    ]
