# Generated by Django 2.0.3 on 2018-06-15 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RedAnt', '0030_auto_20180604_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='ShortName',
        ),
        migrations.RemoveField(
            model_name='projectteam',
            name='ShortName',
        ),
    ]
