# Generated by Django 2.0.3 on 2018-06-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedAnt', '0032_auto_20180616_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectteam',
            name='OutofTime',
            field=models.BooleanField(default=False),
        ),
    ]
